config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/index', to: 'pages#index'

  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :ingredients, except: [:destroy]

  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 150},
          format: { with: VALID_EMAIL_REGEX},
          uniqueness: { case_sensitive: false }
   validates :password, presence: true, length: { minimum: 5 }

    has_many :recipes, dependent: :destroy
    has_secure_password
    validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
    has_many :comments, dependent: :destroy

    has_many :messages, dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true, length: { minimum: 4, maximum: 140 }
  belongs_to :chef
  belongs_to :recipe
  validates :chef_id, presence: true
  validates :recipe_id, presence: true
  default_scope -> { order(updated_at: :desc)}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chef
  validates :content, presence: true
  validates :chef_id, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
   validates :name, presence: true
   validates :description, presence: true, length: { minimum: 5, maximum: 5000 }

   belongs_to :chef
   validates :chef_id, presence: true

   default_scope -> { order(updated_at: :desc)}

   has_many :recipe_ingredients
   has_many :ingredients, through: :recipe_ingredients
   has_many :comments, dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef = Chef.new
  end

  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 4)
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_id] = @chef.id
      cookies.signed[:chef_id] = @chef.id
      flash[:success] = "Welcome #{@chef.chefname} to InstaFood!"
      redirect_to chef_path(@chef)
    else
      render 'new'
    end
  end

  def edit

  end



  def update
     if @chef.update(chef_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to @chef
    else
      render 'edit'
    end
  end

  def destroy
    if !@chef.admin?
    @chef.destroy
    flash[:danger] = "Chef and all associated recipes have been deleted"
    redirect_to chefs_path
    end
  end

private

  def chef_params
    params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
  end

  def set_chef
    @chef = Chef.find(params[:id])
  end

  def require_same_user
    if current_chef != @chef and !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own account"
      redirect_to chefs_path
    end
  end

  def require_admin
    if logged_in? && !current_chef.admin?
      flash[:danger] = "Only administrator's can do that"
      require_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(comment_params)
    @comment.chef = current_chef
    if @comment.save
      ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
    else
      flash[:danger] = "Comment was not created"
      redirect_to :back
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to recipes_path if logged_in?
  end

  def show
  end

  def edit
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :set_recipe, only: [:show, :edit, :update, :destroy]
   before_action :require_user, except: [:index, :show]
   before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 4)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_path
  end


  private

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :description, ingredient_ids: [])
    end

    def require_same_user
      if current_chef != @recipe.chef and !current_chef.admin
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname,
                            class: "img-circle")
  end

end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small blue pt-4 mt-4">

    <!--Footer Links-->
    <div class="container-fluid text-center text-md-left">
        <div class="row">

            <!--First column-->
            <div class="col-md-6">
                <h5 class="text-uppercase">Johnathan Davila</h5>
                <p>This is a webste for people that love food, as much as I do, for now this is the beta version of this app.
                   Stay tuned for the upgraded version in the month to come.
                </p>
            </div>
            <!--/.First column-->

            <!--Second column-->
            <div class="col-md-6">
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                    <li>
                        <%= link_to "Chefs", chefs_path  %>
                    </li>
                    <li>
                        <%= link_to "Recipes", recipes_path %>
                    </li>
                    <li>
                        <%= link_to "Ingredients", ingredients_path %>
                    </li>
                </ul>
            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->



</footer>
<!--/.Footer-->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 cole-md-offset-1">
    <% flash.each do |name, msg| %>
       <div class="alert alert-<%= name %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
              <%= msg %>
       </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "InstaFood", root_path, class: "navbar-brand", id:"logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "What's Cooking?", recipes_path %></li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Recipes <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "What's Cooking?", recipes_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "New Recipe", new_recipe_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <% if logged_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Ingredients <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Ingredients", ingredients_path %></li>
                  <% Ingredient.all.each do |ingredient| %>
                      <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
                  <% end %>
                  <% if logged_in? && current_chef.admin? %>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "New Ingredient", new_ingredient_path %></li>
              <% end %>
            </ul>
           <% end %>
          </li>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
          <% if logged_in?  %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.capitalize %>'s Profile  <%= "Admin" if current_chef.admin? %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Profile", chef_path(current_chef) %></li>
                <li><%= link_to "Edit Profile", edit_chef_path(current_chef) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instafood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <%= render 'layouts/messages' %>
   <div class="container">
      <%= yield %>
   </div>
      <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<div class="jumbotron center">
  <h1>Welcome to Instafood</h1>
  <h2> <i>A community for Foodies'</i> </h2>
   <p><%= link_to "Sign Up Today", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

 <div class="row">
        <div class="col-lg-4">
          <h2>Will Fill Out Later</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-xlarge" href="#" role="button">View details &raquo;</a></p>
        </div>
            <div class="col-lg-4">
              <h2>The Buttons Below</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa    justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-xlarge" href="#" role="button">View details &raquo;</a></p>
            </div>
        <div class="col-lg-4">
          <h2>Do Not Work For Now</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn btn-xlarge" href="#" role="button">View detai ls &raquo;</a></p>
        </div>
  </div>

  <br>
  <br>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"> <%= title %></h1>

     <hr>